FROM node:14.15.4

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR /home/project
COPY package.json .babelrc ./
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/
COPY apiserver ./apiserver/

RUN cd /home/project
RUN npm i
RUN npm run build

CMD [ "npm", "run", "api" ]
CMD [ "npm", "run", "start" ]

EXPOSE 3000

# CMD ["pm2-docker", "process.yml"]
