FROM ubuntu:focal 

RUN sudo apt install nginx
COPY docker/nginx.conf /etc/nginx/nginx.conf
RUN cd /home
RUN mkdir project
RUN sudo systemctl reload nginx
RUN sudo systemctl start nginx


WORKDIR /home/project
COPY package.json .babelrc ./
COPY apiserver ./apiserver/
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN cd /home/project
RUN npm i
RUN npm run build

COPY docker/services/nodeHomepage.service /etc/systemd/system/nodeHomepage.service
COPY docker/services/nodeApi.service /etc/systemd/system/nodeApi.service
RUN sudo systemctl daemon-reload
RUN sudo systemctl enable nodeApi
RUN sudo systemctl enable nodeHomepage
RUN sudo systemctl start nodeApi
RUN sudo systemctl start nodeHomepage

EXPOSE 80
ENTRYPOINT node dist/server.generated.js


