FROM ubuntu:focal 

ENV NODE_VERSION=14.15.4
RUN apt-get update && \
	apt-get install wget curl ca-certificates rsync -y
RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" &&  nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
RUN cp /root/.nvm/versions/node/v${NODE_VERSION}/bin/node /usr/bin/
RUN cp /root/.nvm/versions/node/v${NODE_VERSION}/bin/npm /usr/bin/
RUN /root/.nvm/versions/node/v${NODE_VERSION}/bin/npm install  leasot@latest -g
RUN apt-get install nginx -y
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
RUN cd /home
RUN mkdir project
RUN systemctl reload nginx
RUN systemctl start nginx


WORKDIR /home/project
COPY package.json .babelrc ./
COPY apiserver ./apiserver/
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN cd /home/project
RUN npm i
RUN npm run build

COPY docker/services/nodeHomepage.service /etc/systemd/system/nodeHomepage.service
COPY docker/services/nodeApi.service /etc/systemd/system/nodeApi.service
RUN systemctl daemon-reload
RUN systemctl enable nodeApi
RUN systemctl enable nodeHomepage
RUN systemctl start nodeApi
RUN systemctl start nodeHomepage

EXPOSE 80
ENTRYPOINT node dist/server.generated.js


