FROM node:lts-alpine3.12

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR /home/project
COPY package.json ./
RUN npm i
COPY .babelrc ./
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN npm run build:dll

CMD [ "npm", "run", "dev" ]

EXPOSE 3000

