FROM node:lts-alpine3.12

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR  /home/project
COPY package.json .babelrc ./

RUN npm i
COPY apiserver ./apiserver/

EXPOSE 3200
CMD [ "npm", "run", "api" ]
