FROM node:14.15.4

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR  /home/project
COPY package.json .babelrc .
COPY apiserver .

RUN cd /home/project
RUN npm i

EXPOSE 3200
ENTRYPOINT nodemon apiserver/main.js

# CMD ["pm2-docker", "process.yml"]
