FROM node:14.15.4

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR /home/project
COPY package.json .babelrc .
COPY public .
COPY src .
COPY webpack .

RUN cd /home/project
RUN npm i
RUN npm run build

EXPOSE 3100
ENTRYPOINT node dist/server.generated.js

# CMD ["pm2-docker", "process.yml"]
