FROM node:lts-alpine3.12

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR /home/project
COPY package.json ./
RUN npm i
COPY .babelrc ./
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN cd /home/project
RUN npm run build

CMD [ "npm", "run", "start" ]

EXPOSE 3000

# CMD ["pm2-docker", "process.yml"]
