FROM ubuntu:focal

RUN apt update
# We directly answer the questions asked using the printf statement
RUN printf 'y\n1\n\1n' | apt install nodejs
RUN apt install -y npm
RUN apt-get install nginx -y
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
RUN cd /home
RUN mkdir project
RUN npm install pm2 -g


WORKDIR /home/project
COPY package.json .babelrc ./
COPY apiserver ./apiserver/
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN cd /home/project
RUN npm i
RUN npm run build
RUN pm2 start --name apiserver apiserver/main.js
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
ENTRYPOINT pm2 start --name ssr  dist/server.generated.js


