FROM node:14.15.4

RUN npm install pm2 -g
RUN cd /home
RUN mkdir project

WORKDIR /home/project
COPY package.json .babelrc ./
COPY public ./public/
COPY src ./src/
COPY webpack ./webpack/

RUN cd /home/project
RUN npm i
RUN npm run build

EXPOSE 3000
ENTRYPOINT node dist/server.generated.js

# CMD ["pm2-docker", "process.yml"]
