version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        depends_on:
            - api
            - ssr
        ports:
            - "80:80"
        environment:
            - ENABLE_SSL=0
            - DOCKERMODE=true            
    ssr:
        build:
            context: .
            dockerfile: Dockerfile.ssr
        environment:
            - NGINX_HOST=nginx
            - ENABLE_SSL=0
            - DOCKERMODE=true            
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        environment:
            - ENABLE_SSL=0
            - DOCKERMODE=true            
