export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_POERTFOLIO_SUCCESS = 'LOAD_POERTFOLIO_SUCCESS';
export const LOAD_DERAILS_SUCCESS = 'LOAD_DERAILS_SUCCESS';
export const LOAD_RECENT_WORKS_SUCCESS = 'LOAD_RECENT_WORKS_SUCCESS';

export const CHANGE_XSNAV_OPEN = 'CHANGE_XSNAV_OPEN';

